services:
  app:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - redis
      - db
    volumes:
      - ./data
    environment:
      - REDIS_HOST=redis
    

  redis:
    image: redis
    volumes:
      - redis-data:/data

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydatabase
      DB_ROOT_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
    